[phases.setup]
nixPkgs = ["python3", "gcc", "python3-setuptools", "python3-wheel"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x start.sh"]

[start]
cmd = "gunicorn app:app" 