services:
  - type: web
    name: cap-agent-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
      - key: DATABASE_URL
        fromDatabase:
          name: cap-db
          property: connectionString

databases:
  - name: cap-db
    databaseName: cap
    user: cap_user
    plan: free
